### ISSUE TITLE
Scrum Update - Iteration 1

### ISSUE THREAD

**Issue by meinna** [crismihailescu/socialMotivator#1]

**Comment by truzopus** [comment]
Last week, we discussed different project ideas and finally decided on a social motivator web-app as the most viable one. The difficulties included coming up with a project because we haven't learnt enough to know the boundaries of a good project and if it can be fitted into a good timeframe. We figured out that we would probably add/change requirements as we learn more about the course. Next week, I would try to get the react-router-dom set up and try navigating to different pages.

**Comment by meinna** [comment]
This iteration I wrote an introduction to help find team members, came up with pros/cons for our two project ideas to narrow down to a final selection, and came up with project task requirements that could be slotted into minimal, standard or stretch requirements. No major challenges were encountered this iteration. The hardest part of this iteration was generating suitable project ideas that were both interesting and useful. The first part of this coming iteration I will focus on learning the basics of react. I will then use this knowledge to create components and page basics for our project.

**Comment by crismihailescu** [comment]
After joining my group, I helped suggest the idea that we eventually shaped into our project, contributed to coming up with the requirements, and drew the UI mockups for our project. The main challenge we faced was trying to create realistic requirements without really knowing much of the stack we are going to learn this term, and of course ideation is also always challenging, but all things considered I think we had lots of great ideas and eventually settled on one we were all happy with. In these next two weeks I'll be focusing on learning React since I am not familiar with it, and getting started on the UI for our project by creating our components; I imagine we'll split the work up between all our teammates.

**Comment by GaussianSums** [comment]
This iteration I found team members and participated in the discussion around the main focus of the project, and helped come up with requirements for the project. The biggest challenge so far has been trying to make estimates of what can reasonably go into a project while being unfamiliar with the technologies we will be using. My main focus over the next iteration will be to work hard on learning react so that I can participate meaningfully in the creation of our project.
