### ISSUE TITLE
Scrum #3

### ISSUE THREAD

**Issue by meinna** [crismihailescu/socialMotivator#36]
This past iteration I worked on the user dashboard and account settings pages of our website. No major issues were encounted, but one challenge was dealing with competing css from components that are located within other components. This upcoming iteration I plan to learn all about mongoDB so I can start to hook our frontend up with our backend. 

r7e9

**Comment by truzopus** [comment]
This past iteration, I completed the sign in/sign up page. Next week, I hope to hook that up to the backend and set up collections and confirm the data structure of the group. Also I will work on the leaderboard and the view activities page. The real challenge will be incorporating redux-saga with the backend and linking that to the frontend.
r7k2b

**Comment by crismihailescu** [comment]
The past two weeks I worked on redesigning the home page to look more modern, and to have dynamic carousels across the page, instead of a drop down menu showing just one carousel. This next iteration I will be working on the leaderboard with Truman and on the company dashboard. The most challenging thing these past two weeks (and something I'm still trying to get better at) is styling with CSS, especially when trying to make layouts that align properly (and look good).

**Comment by GaussianSums** [comment]
Over the past two weeks, I worked largely on two components: I made our navbar menu collapsable, and updated a pop-up modal to have a detailed card view. Over the next two weeks I will be working with the rest of the team to help where I can, and updating our existing components to work with a server. I am looking forward to learning more about express and hooking up a backend.
